disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - redundant_string_enum_value
  - identifier_name
  - file_length
  - implicit_getter
  - type_name
  - todo
  - operator_whitespace
  - cyclomatic_complexity
  - type_body_length
  - force_try
  - force_cast
  - inclusive_language
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - FhirStu3/Sources
  - FhirStu3/Tests
  - FhirR4/Sources
  - FhirR4/Tests

excluded:
  - FhirR4/Sources/ModelsR4
  - FhirR4/Sources/FMCore

line_length: 300
function_body_length:
  warning: 600
  error: 800
large_tuple:
  warning: 3
  error: 4
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
