= Data4Life Core iOS SDK
:link-repository: https://github.com/d4l-data4life/d4l-fhir-ios
:library_version: 0.23.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]


++++
<div align="center">
    <p><!-- PROJECT LOGO -->
        <a href="https://github.com/d4l-data4life/d4l-data4life/d4l-fhir-ios">
            <img src="assets/images/d4l-logo.svg" width="150"/>
        </a>
    </p>
    <p><!-- PROJECT TITLE -->
        <h3>Data4Life FHIR SDK</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        Minimal FHIR standard models and data types for iOS
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/d4l-data4life/d4l-data4life/d4l-fhir-ios/issues">Report Bug</a>
        ·
        <a href="https://github.com/d4l-data4life/d4l-data4life/d4l-fhir-ios/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/d4l-data4life/d4l-data4life/d4l-fhir-ios/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a href="https://github.com/d4l-data4life/d4l-fhir-ios/actions">
            <img src="https://github.com/d4l-data4life/d4l-fhir-ios/actions/workflows/pr-test.yml/badge.svg" alt="Build Status"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a>
            <img src="assets/images/badge-manager-support.svg" alt="Manager"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++


[discrete]
=== Table Of Contents
toc::[]

== About The Project

Minimal FHIR standard models and data types for iOS.

link:https://github.com/smart-on-fhir/Swift-FHIR[Swift-FHIR] was used as inspiration for this project

link:https://github.com/apple/FHIRModels[Apple-FHIR] R4 models were (temporarily) ported over.

== Installation

=== Swift Package Manager

To install with Swift package manager, select your project’s Swift Packages tab, and add our repository url, either as ssh or https url:

[source, terminal]
----
https://github.com/d4l-data4life/d4l-fhir-ios.git
----

OR

[source, terminal]
----
git@github.com:d4l-data4life/d4l-fhir-ios.git
----

In the next step, select the latest version, and then import the `Data4LifeFHIR` or `ModelsR4` framework (or both) in your target.

== Documentation 

Further documentation on how to use it can be found link:docs/v0.22.1/index.html[here]

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.
* link:DEVELOPING.adoc[Developing] for details about our development process and how to build and test the project.

== Copyright and License

Copyright (c) 2021 D4L data4life gGmbH / All rights reserved. Please refer to our link:LICENSE[License] for further details.
