:toc: left
:icons: font
:source-highlighter: prettify
//:numbered:
:stylesdir: styles/
:imagesdir: images/
:linkcss:

// Variables:
:icons: font
:compname-short: D4L
:compname-legal: D4L data4life gGmbH
:compname: data4life
:email-contact: me@data4life.care
:email-docs: docs@data4life.care
:url-company: https://www.data4life.care
:url-docs: https://d4l.io
:prod-name: data4life
:sdk-name: data4life FHIR framework
:app-name: data4life
:app-plat: iOS
:phdp-plat: Personal Health Data Platform
:sw-name: {compname} {prod-name}
:sw-version: {project-version}
:pub-type: Internal
:pub-version: 1.00
:pub-status: draft
:pub-title: {software-name} {pub-type}
:copyright-year: 2019
:copyright-statement: (C) {copyright-year} {compname-legal}. All rights reserved.

== Using the {app-plat} {sdk-name}

As part of our integration efforts with our partners, {compname} provides frameworks for the following platforms:

* iOS (Swift)
* Android (Java)
* Web (JavaScript)

The {sdk-name} encapsulates a type safe definition of a minimal set of FHIR standard models and data types, to be used in {app-plat}.
It includes also some helpers to create some specific FHIR Elements in an easier way, for widely used use cases.

=== Software requirements
The {app-plat} {sdk-name} has the following software requirements:

* Xcode 12.4 or later
* iOS 13.0 or later
* Swift 5.3 or later

=== Installing dependency managers

This section describes how you get the SDK up and running.
Use the following for dependency management for the {app-plat} {sdk-name}:

* *Carthage* is a dependency manager written in Swift.
It builds your dependencies and provides you with binary frameworks while you retain control over your project structure and setup.

* *CocoaPods* is a dependency manager for Swift and Objective-C Cocoa projects.
The file with the specification that describes the dependencies of the targets of one or more Xcode projects is called `Podfile`.

==== Carthage

To install with Carthage, use the following:

----
github "d4l-data4life/d4l-fhir-ios"
----

[NOTE]
====
The framework has a few <<Dependencies of the SDK, dependencies>>.
You must add them and link them manually with icon:external-link[] https://github.com/Carthage/Carthage#nested-dependencies[your project].
====


==== CocoaPods

To add a private CocoaPods specs repository to the `Podfile`, use the following:

[source, ruby]
----
source 'https://github.com/d4l-data4life/d4l-cocoapods-specs.git'
----

To add the framework for STU3 support to the `Podfile`, use the following:

[source, ruby]
----
pod 'Data4LifeFHIR'
----

To add the framework for R4 support to the `Podfile`, use the following:

[source, ruby]
----
pod 'ModelsR4'
----

For more info, see icon:eye[] the https://github.com/d4l-data4life/d4l-cocoapods-specs/blob/master/README.md[CocoaPods specs repository] readme file.

==== Dependencies of the FHIR Framework

The {sdk-name} has the following dependency:

* https://github.com/d4l-data4life/d4l-utils-ios[Data4LifeSDKUtils] icon:external-link[] – {compname} Set of private utils used in data4Life Frameworks

=== Known Issues

==== FHIR standard

* String / Integer / Decimal / Bool / URL / Base64Binary should inherit Element
* All properties dealing with binary data are represented as base64 String
