default_platform :ios

project = "Data4LifeFHIR"
projectR4 = "ModelsR4"

repository = "d4l-data4life/d4l-fhir-ios"
framework_binary_path = "build/" + project + ".framework.zip"
podspec_stu3_path = '../Data4LifeFHIR.podspec'
podspec_r4_path = '../ModelsR4.podspec'
podspec_core_path = '../Data4LifeFHIRCore.podspec'
podspec_repo_name = 'd4l-data4life'
podspect_repo_url = 'https://github.com/d4l-data4life/d4l-cocoapods-specs.git'
device = "iPhone 12"

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(
      scheme: project,
      derived_data_path: "build/DerivedData",
      devices: device,
      clean: true
    )
    scan(
      scheme: projectR4,
      derived_data_path: "build/DerivedData",
      devices: device,
      clean: false
    )

    Dir.chdir("..") do
      sh("pod spec lint --sources='git@github.com:d4l-data4life/d4l-cocoapods-specs.git,https://github.com/CocoaPods/Specs'")
    end
  end

  desc "Run linter and autocorrect issues"
  lane :lint do
      swiftlint(
        mode: :autocorrect,
        config_file: ".swiftlint.yml"
      )
  end

  desc "Generate All FHIR code"
  lane :generate_all do | options |
      fhir_stu3 xcode:true
      fhir_r4_helpers
      fhir_r4_tests
      lint
  end

  desc "Generate FHIR STU3 models"
  lane :generate_stu3_models do | options |
      fhir_stu3 xcode:true
  end

  desc "Generate FHIR R4 Extesnions"
  lane :generate_r4_helpers do | options |
      fhir_r4_helpers
  end

  desc "Generate FHIR R4 tests"
  lane :generate_r4_tests do | options |
      fhir_r4_tests
  end

  desc "Package and release framework"
  desc "#### Options"
  desc " * **`version`** (required): The new version of the framework"
  desc " * **`api_token`** (required): Github API token"
  desc " * **`allow_dirty_branch`**: Allows the git branch to be dirty before continuing. Defaults to false"
  desc " * **`remote`**: The name of the git remote. Defaults to `origin`. (`DEPLOY_REMOTE`)"
  desc " * **`allow_branch`**: The name of the branch to build from. Defaults to `main`. (`DEPLOY_BRANCH`)"
  desc " * **`skip_git_pull`**: Skips pulling the git remote. Defaults to false"
  desc " * **`is_prerelease`**: Marks GitHub release as Pre-release. Defaults to false"
  lane :release_framework do | options |
    if options[:allow_dirty_branch] != true
      ensure_git_status_clean
    end

    # Update the version
    if !options[:version]
      raise "No version specified!".red
    end

    if !options[:api_token]
      raise "No api_token specified!".red
    end

    version = options[:version]
    is_prerelease = options[:is_prerelease] ||= false

    remote = options[:remote] ? options[:remote] : (ENV["DEPLOY_REMOTE"] ? ENV["DEPLOY_REMOTE"] : "origin")
    allowed_branch = options[:allow_branch] ? options[:allow_branch] : (ENV["DEPLOY_BRANCH"] ? ENV["DEPLOY_BRANCH"] : "release/#{version}")
    ensure_git_branch(branch: allowed_branch)

    if options[:skip_git_pull] != true
      sh("git pull #{remote} #{allowed_branch}")
    end

    # Parse changelog data
    changelog_path = options[:changelog_path] ? options[:changelog_path] : "../CHANGELOG.md"
    changelog_data = File.read(changelog_path)
    # Try to find all markdown headers and split
    changelog_sections = changelog_data.split(/\#{2,3}\s/)
    # Look out for new section of the newest version
    current_changelog_index = changelog_sections.index { |h| h.start_with?("[#{version}]")}

    unless current_changelog_index
      UI.error("Please add all changes of the version to the CHANGELOG.md file")
    end

    # Get all split for this version and combine them again to one text
    changelog_header_indices = changelog_sections.each_with_index.select {|s, _| s.match(/^\[([0-9]+)\.([0-9]+)\.([0-9]+)\]/) }.map(&:last)
    next_changelog_index = changelog_header_indices.index { |h| h == current_changelog_index } + 1
    changelog = "### " + changelog_sections[current_changelog_index + 1...changelog_header_indices[next_changelog_index]].join("### ")

    if prompt(text: "#{version} has been prepped for release. If you have any additional changes you would like to make to the README or CHANGELOG, please do those before continuing. Would you like to commit, tag, and push #{version} to #{remote}?".green, boolean: true, ci_input:"y")
      increment_version_number(
        xcodeproj: "#{project}.xcodeproj",
        version_number: version
      )

      update_podspec_version(version: version)

      git_commit(
        path: ".",
        message: "Preparing for the #{version} release"
      )

      push_to_git_remote(
        remote: remote,
        tags: false
      )

      add_git_tag(
        tag: "#{version}"
      )
    else
      Helper.log.info "When finished, commit your changes and create your tag.".red
    end

    build_xcframework(version: version)
    archiveAllFrameworksPath = allXcFrameworksArchivePath(version)
    archiveStu3Path = stu3XcFrameworkArchivePath(version)
    archiveR4Path = r4XcFrameworkArchivePath(version)
    archiveCorePath = coreXcFrameworkArchivePath(version)

    # Post new release to GitHub
    gh_release(
      version: version,
      api_token:options[:api_token],
      changelog: changelog,
      is_prerelease: is_prerelease,
      asset1: archiveAllFrameworksPath,
      asset2: archiveStu3Path,
      asset3: archiveR4Path,
      asset4: archiveCorePath
    )

    push_stu3_podspec
    push_r4_podspec
  end

  desc "Build xcframework for distribution"
  lane :build_xcframework do |options|
    if options[:version] == nil
        raise "Missing release version".red
    end

    Dir.chdir("..") do
      root = Dir.pwd
      configuration = "Release"
      buildPath = "xcbuild"

      coreXcFrameworkPath = "#{project}Core.xcframework"
      stu3xcFrameworkPath = "#{project}.xcframework"
      r4xcFrameworkPath = "#{projectR4}.xcframework"

      archiveAllFrameworksPath = allXcFrameworksArchivePath(options[:version])
      archiveCorePath = coreXcFrameworkArchivePath(options[:version])
      archiveStu3Path = stu3XcFrameworkArchivePath(options[:version])
      archiveR4Path = r4XcFrameworkArchivePath(options[:version])

      if File.exist?(buildPath)
        sh "rm -rf #{buildPath}"
      end
      if File.exist?(stu3xcFrameworkPath)
        sh "rm -rf #{stu3xcFrameworkPath}"
      end
      if File.exist?(r4xcFrameworkPath)
        sh "rm -rf #{r4xcFrameworkPath}"
      end
      if File.exist?(coreXcFrameworkPath)
        sh "rm -rf #{coreXcFrameworkPath}"
      end

      if File.exist?(archiveAllFrameworksPath)
        sh "rm #{archiveAllFrameworksPath}"
      end
      if File.exist?(archiveStu3Path)
        sh "rm #{archiveStu3Path}"
      end
      if File.exist?(archiveR4Path)
        sh "rm #{archiveR4Path}"
      end
      if File.exist?(archiveCorePath)
        sh "rm #{archiveCorePath}"
      end

      sh "rm -rf #{buildPath}"
      sh "rm -rf #{coreXcFrameworkPath}"
      sh "xcodebuild archive -scheme #{project}Core -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{project}Core-iphonesimulator.xcarchive -destination 'generic/platform=iOS Simulator' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild archive -scheme #{project}Core -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{project}Core-iphoneos.xcarchive -destination 'generic/platform=iOS' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild -create-xcframework \
          -framework #{buildPath}/#{configuration}/#{project}Core-iphonesimulator.xcarchive/Products/Library/Frameworks/#{project}Core.framework \
          -framework #{buildPath}/#{configuration}/#{project}Core-iphoneos.xcarchive/Products/Library/Frameworks/#{project}Core.framework \
          -output #{coreXcFrameworkPath}"

      sh "rm -rf #{buildPath}"
      sh "rm -rf #{stu3xcFrameworkPath}"
      sh "xcodebuild archive -scheme #{project} -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{project}-iphonesimulator.xcarchive -destination 'generic/platform=iOS Simulator' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild archive -scheme #{project} -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{project}-iphoneos.xcarchive -destination 'generic/platform=iOS' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild -create-xcframework \
          -framework #{buildPath}/#{configuration}/#{project}-iphonesimulator.xcarchive/Products/Library/Frameworks/#{project}.framework \
          -framework #{buildPath}/#{configuration}/#{project}-iphoneos.xcarchive/Products/Library/Frameworks/#{project}.framework \
          -output #{stu3xcFrameworkPath}"

      sh "rm -rf #{buildPath}"
      sh "rm -rf #{r4xcFrameworkPath}"
      sh "xcodebuild archive -scheme #{projectR4} -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{projectR4}-iphonesimulator.xcarchive -destination 'generic/platform=iOS Simulator' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild archive -scheme #{projectR4} -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{projectR4}-iphoneos.xcarchive -destination 'generic/platform=iOS' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild -create-xcframework \
          -framework #{buildPath}/#{configuration}/#{projectR4}-iphonesimulator.xcarchive/Products/Library/Frameworks/#{projectR4}.framework \
          -framework #{buildPath}/#{configuration}/#{projectR4}-iphoneos.xcarchive/Products/Library/Frameworks/#{projectR4}.framework \
          -output #{r4xcFrameworkPath}"

        sh "zip -r #{archiveAllFrameworksPath} #{stu3xcFrameworkPath} #{r4xcFrameworkPath} #{coreXcFrameworkPath} LICENSE"
        sh "zip -r #{archiveCorePath} #{coreXcFrameworkPath}"
        sh "zip -r #{archiveStu3Path} #{stu3xcFrameworkPath}"
        sh "zip -r #{archiveR4Path} #{r4xcFrameworkPath}"

        sh "rm -rf #{stu3xcFrameworkPath}"
        sh "rm -rf #{r4xcFrameworkPath}"
        sh "rm -rf #{coreXcFrameworkPath}"
    end
  end

  desc "Build xcframework for distribution"
  lane :build_fhir_xcframework_test do |options|
    if options[:version] == nil
        raise "Missing release version".red
    end

    Dir.chdir("..") do
      root = Dir.pwd
      configuration = "Release"
      buildPath = "xcbuild"

      stu3xcFrameworkPath = "#{project}.xcframework"
      archiveStu3Path = stu3XcFrameworkArchivePath(options[:version])

      if File.exist?(buildPath)
        sh "rm -rf #{buildPath}"
      end
      if File.exist?(stu3xcFrameworkPath)
        sh "rm -rf #{stu3xcFrameworkPath}"
      end
      if File.exist?(archiveStu3Path)
        sh "rm #{archiveStu3Path}"
      end

      sh "rm -rf #{buildPath}"
      sh "rm -rf #{stu3xcFrameworkPath}"
      sh "xcodebuild archive -scheme #{project} -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{project}-iphonesimulator.xcarchive -destination 'generic/platform=iOS Simulator' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild archive -scheme #{project} -configuration #{configuration} -archivePath #{buildPath}/#{configuration}/#{project}-iphoneos.xcarchive -destination 'generic/platform=iOS' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      sh "xcodebuild -create-xcframework \
          -framework #{buildPath}/#{configuration}/#{project}-iphonesimulator.xcarchive/Products/Library/Frameworks/#{project}.framework \
          -framework #{buildPath}/#{configuration}/#{project}-iphoneos.xcarchive/Products/Library/Frameworks/#{project}.framework \
          -output #{stu3xcFrameworkPath}"

        sh "zip -r #{archiveStu3Path} #{stu3xcFrameworkPath}"
        #sh "rm -rf #{stu3xcFrameworkPath}"
    end
  end

  desc "Upload to a github release"
  lane :gh_release do |options|

    if options[:version] == nil
        raise "Missing release version".red
    end

    if options[:api_token] == nil
        raise "Missing api token".red
    end

    if options[:asset1] == nil
        raise "Missing asset".red
    end

    if options[:asset2] == nil
        raise "Missing asset".red
    end

    if options[:asset3] == nil
        raise "Missing asset".red
    end

    if options[:asset4] == nil
        raise "Missing asset".red
    end

    isPrerelease = options[:is_prerelease]
    if isPrerelease == nil
        isPrerelease = true
    end

    changelog = options[:changelog]
    if changelog == nil
       changelog = "Pre-release"
    end

    set_github_release(
      repository_name: repository,
      api_token: options[:api_token],
      name: "#{options[:version]}",
      tag_name: options[:version],
      description: changelog,
      is_prerelease: isPrerelease,
      upload_assets: [options[:asset1], options[:asset2], options[:asset3], options[:asset4]]
    )
  end

  desc "Update podspecs version"
  lane :update_podspec_version do | options |
    UI.user_error!("Could not find podspec file at path #{podspec_stu3_path}") unless File.exist?(podspec_stu3_path)
    UI.user_error!("Could not find podspec file at path #{podspec_r4_path}") unless File.exist?(podspec_r4_path)
    UI.user_error!("Could not find podspec file at path #{podspec_core_path}") unless File.exist?(podspec_core_path)

    if !options[:version]
      raise "No version specified!".red
    end

    new_version = options[:version]

    podspec_stu3_content = File.read(podspec_stu3_path)
    updated = podspec_stu3_content.gsub(/"([0-9]+)\.([0-9]+)\.([0-9]+)\-?([0-9a-zA-Z]*)\.?([0-9a-zA-Z]*)"/, "\"#{new_version}\"")
    File.write(podspec_stu3_path, updated)

    podspec_r4_content = File.read(podspec_r4_path)
    updated = podspec_r4_content.gsub(/"([0-9]+)\.([0-9]+)\.([0-9]+)\-?([0-9a-zA-Z]*)\.?([0-9a-zA-Z]*)"/, "\"#{new_version}\"")
    File.write(podspec_r4_path, updated)

    podspec_core_content = File.read(podspec_core_path)
    updated = podspec_core_content.gsub(/"([0-9]+)\.([0-9]+)\.([0-9]+)\-?([0-9a-zA-Z]*)\.?([0-9a-zA-Z]*)"/, "\"#{new_version}\"")
    File.write(podspec_core_path, updated)
  end

  desc "Push new core podspec to repo"
  lane :push_core_podspec do
    repo_list = sh "bundle exec pod repo list"
    if !repo_list.include? podspec_repo_name
     sh "bundle exec pod repo add #{podspec_repo_name} #{podspect_repo_url}"
    end

    sh "bundle exec pod repo push #{podspec_repo_name} #{podspec_core_path} --allow-warnings"
  end

  desc "Push new stu3 podspec to repo"
  lane :push_stu3_podspec do
    repo_list = sh "bundle exec pod repo list"
    if !repo_list.include? podspec_repo_name
     sh "bundle exec pod repo add #{podspec_repo_name} #{podspect_repo_url}"
    end

    sh "bundle exec pod repo push #{podspec_repo_name} #{podspec_stu3_path} --allow-warnings"
  end

  desc "Push new r4 podspec to repo"
  lane :push_r4_podspec do
    repo_list = sh "bundle exec pod repo list"
    if !repo_list.include? podspec_repo_name
     sh "bundle exec pod repo add #{podspec_repo_name} #{podspect_repo_url}"
    end

    sh "bundle exec pod repo push #{podspec_repo_name} #{podspec_r4_path} --allow-warnings"
  end

  desc "Generate docs per version using Asciidoctor"
  lane :generate_docs do | options |
    if options[:version] == nil
        raise "Missing version".red
    end

    version = options[:version]
    arguments = "project-version=" + version
    input_path = "../asciidoc/index.adoc"
    output_folder_path = "../docs/" + version
    output_filename_path = "index.html"
    output_final_path = output_folder_path + "/" + output_filename_path

    sh "rm -rf #{output_folder_path}"
    sh "mkdir #{output_folder_path}"
    sh "bundle exec asciidoctor -b html5 -d book -o #{output_final_path} -a #{arguments} #{input_path} "
  end

  def allXcFrameworksArchivePath(version)
     return "XCFrameworks-#{version}.zip"
  end

  def stu3XcFrameworkArchivePath(version)
     return "Data4LifeFHIR-xcframework-#{version}.zip"
  end

  def r4XcFrameworkArchivePath(version)
     return "ModelsR4-xcframework-#{version}.zip"
  end

  def coreXcFrameworkArchivePath(version)
     return "Data4LifeFHIRCore-xcframework-#{version}.zip"
  end
end
