name: D4L FHIR CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, macos]
    steps:
    - name: Display runner context
      run: hostname -s
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
    - name: test
      run: bundle exec fastlane test
